FROM node:18
WORKDIR /backend
COPY package*.json ./
RUN npm install
RUN apt-get update && apt-get install -y default-mysql-client \
    && rm -rf /var/lib/apt/lists/*
COPY . .
EXPOSE 3001
CMD ["npm", "start"]
