services:
  # Servizio MySQL (Database)
  db:
    build:
      context: ./db  
    container_name: mysql_container
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: armonizzazione_percorsi
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # FRONTEND: React con Bootstrap
  frontend:
    build:
      context: ./frontend  
    container_name: frontend_container
    ports:
      - "5500:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  db_data: